trigger:
  - master

jobs:
  - job: buildjob
    displayName: Build and Package Game of life
    pool:
      vmImage: ubuntu-22.04
    steps:
      - task: Maven@3
        inputs:
          mavenPOMFile: 'pom.xml'
          goals: 'package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
      - task: CopyFiles@2
        inputs:
          Contents: "**/target/gameoflife.war"
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: GameOfLifeArtifacts

  - job: dockerjob
    displayName: 'Build and Push Docker image'
    pool:
      vmImage: ubuntu-22.04
    steps:
      - task: Docker@2
        displayName: 'Build Docker image'
        inputs:
          command: 'build'
          containerRegistry: 'Docker-Hub-Connection'
          repository: 'shivakrishna99/az-gameoflife'
          dockerfile: '**/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: |
            latest
            $(Build.BuildId)
      - task: Docker@2
        displayName: 'Push Docker image'
        inputs:
          command: 'push'
          containerRegistry: 'Docker-Hub-Connection'
          repository: 'shivakrishna99/az-gameoflife'
          tags: |
            latest
            $(Build.BuildId)

  - job: publishjob
    displayName: 'Publish Artifacts'
    pool:
      vmImage: ubuntu-22.04
    steps:
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/target'
          ArtifactName: 'gameoflife'
